name: Computers xEA - Jamf Site

on:
  watch:
    types: [started]

  workflow_dispatch: # manual trigger
      inputs:
        logLevel:
          description: 'Enable debug mode'
          required: true
          default: 'debug'
          type: choice
          options:
          - info
          - warning
          - debug

jobs:
  jamf-pro-api:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - name: Checkout Repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2 Pin SHA1 hash instead of version
      with:
        fetch-depth: 1
        
    - name: Install Python Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
  
    - name: Run API Python Script
      run: |
        python3 Action-Jamf_Pro_API-Update_xEA-Jamf-Site.py
      env:
        JSS_URL: ${{ secrets.JAMF_URL }}
        JSS_CLIENT_ID: ${{ secrets.JAMF_CLIENT_ID }}
        JSS_CLIENT_SECRET: ${{ secrets.JAMF_CLIENT_SECRET }}
        JSS_xEA_NAME: "xEA - Jamf Site"
        JSS_xEA_ID: "1"
          
    - name: Send the results on what happened
      run: |
        echo "### Jamf API Action Completed! :rocket:" >> $GITHUB_STEP_SUMMARY
